FROM ubuntu:20.04

ENV DEBIAN_FRONTEND noninteractive
ENV QT_QUICK_BACKEND software
ENV QT_QPA_PLATFORM offscreen

RUN apt-get clean
RUN apt-get update && \
    apt-get install -y devscripts equivs

RUN apt install gnupg dirmngr ca-certificates curl --no-install-recommends
RUN curl -s https://dl.jami.net/public-key.gpg | tee /usr/share/keyrings/jami-archive-keyring.gpg > /dev/null
RUN sh -c "echo 'deb [signed-by=/usr/share/keyrings/jami-archive-keyring.gpg] https://dl.jami.net/internal/ubuntu_20.04/ jami main' > /etc/apt/sources.list.d/jami.list"
RUN apt-get update && apt-get install libqt-jami -y

RUN apt-get install -y -o Acquire::Retries=10 \
        python3 \
        git \
        autoconf \
        automake \
        autopoint \
        cmake \
        libtool \
        libdbus-1-dev \
        libdbus-c++-dev \
        libargon2-0-dev \
        libcanberra-gtk3-dev \
        libclutter-gtk-1.0-dev \
        libclutter-1.0-dev \
        libglib2.0-dev \
        libgtk-3-dev \
        libnotify-dev \
        yasm \
        nasm \
        autotools-dev \
        gettext \
        libpulse-dev \
        libasound2-dev \
        libexpat1-dev \
        libpcre3-dev \
        libyaml-cpp-dev \
        libboost-dev \
        libxext-dev \
        libxfixes-dev \
        libspeex-dev \
        libspeexdsp-dev \
        uuid-dev \
        libavcodec-dev \
        libavutil-dev \
        libavformat-dev \
        libswscale-dev \
        libavdevice-dev \
        libopus-dev \
        libudev-dev \
        libgsm1-dev \
        libjsoncpp-dev \
        libmsgpack-dev \
        libnatpmp-dev \
        libappindicator3-dev \
        libqrencode-dev \
        libnm-dev \
        libwebkit2gtk-4.0-dev \
        libcrypto++-dev \
        libva-dev \
        libvdpau-dev \
        libssl-dev
RUN apt-get install -y pandoc \
        googletest \
        libgtest-dev