FROM ubuntu:20.10

ENV DEBIAN_FRONTEND noninteractive
ENV QT_QUICK_BACKEND software
ENV QT_QPA_PLATFORM offscreen

RUN apt-get clean
RUN apt-get update && \
    apt-get install -y devscripts equivs

RUN apt-get install -y -o Acquire::Retries=10 \
        python3 \
        git \
        autoconf \
        automake \
        autopoint \
        cmake \
        libtool \
        libdbus-1-dev \
        libdbus-c++-dev \
        libargon2-0-dev \
        libcanberra-gtk3-dev \
        libclutter-gtk-1.0-dev \
        libclutter-1.0-dev \
        libglib2.0-dev \
        libgtk-3-dev \
        libnotify-dev \
        qtbase5-dev \
        qttools5-dev \
        qttools5-dev-tools \
        yasm \
        nasm \
        autotools-dev \
        gettext \
        libpulse-dev \
        libasound2-dev \
        libexpat1-dev \
        libpcre3-dev \
        libyaml-cpp-dev \
        libboost-dev \
        libxext-dev \
        libxfixes-dev \
        libspeex-dev \
        libspeexdsp-dev \
        uuid-dev \
        libavcodec-dev \
        libavutil-dev \
        libavformat-dev \
        libswscale-dev \
        libavdevice-dev \
        libopus-dev \
        libudev-dev \
        libgsm1-dev \
        libjsoncpp-dev \
        libmsgpack-dev \
        libnatpmp-dev \
        libappindicator3-dev \
        libqrencode-dev \
        libnm-dev \
        libwebkit2gtk-4.0-dev \
        libcrypto++-dev \
        libva-dev \
        libvdpau-dev \
        libssl-dev
RUN apt-get install -y qtmultimedia5-dev \
        libqt5svg5-dev \
        qtwebengine5-dev \
        qtdeclarative5-dev \
        qtquickcontrols2-5-dev \
        libqt5svg5-dev \
        qml-module-qtquick2 \
        qml-module-qtquick-controls \
        qml-module-qtquick-controls2 \
        qml-module-qtquick-dialogs \
        qml-module-qtquick-layouts \
        qml-module-qtquick-privatewidgets \
        qml-module-qtquick-shapes \
        qml-module-qtquick-window2 \
        qml-module-qtquick-templates2 \
        qml-module-qt-labs-platform \
        qml-module-qtwebengine \
        qml-module-qtwebchannel \
        qml-module-qttest \
        pandoc \
        googletest \
        libgtest-dev