.\" Manpage for jami-qt.
.TH man 8 "08 April 2021" "1.0" "jami-qt man page"
.SH NAME
jami-qt \- Qt client for jami.net
.SH SYNOPSIS
jami-qt [options]
.SH DESCRIPTION
jami-qt is a qt client for jami.net
.SH OPTIONS
.B \-v, \-\-version
Display the version and exit.
.TP
.B \-d, \-\-debug
Enable debug.
.TP
.B \-h, \-\-help
Display help text and exit.
.SH SEE ALSO
dring(1)
.SH AUTHOR
Alexandre Viau (alexandre.viau@savoirfairelinux.net)
