/****************************************************************************
 *   Copyright (C) 2015 by Savoir-Faire Linux                               *
 *   Author : Emmanuel Lepage Vallee <emmanuel.lepage@savoirfairelinux.com> *
 *                                                                          *
 *   This library is free software; you can redistribute it and/or          *
 *   modify it under the terms of the GNU Lesser General Public             *
 *   License as published by the Free Software Foundation; either           *
 *   version 2.1 of the License, or (at your option) any later version.     *
 *                                                                          *
 *   This library is distributed in the hope that it will be useful,        *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of         *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU      *
 *   Lesser General Public License for more details.                        *
 *                                                                          *
 *   You should have received a copy of the GNU General Public License      *
 *   along with this program.  If not, see <http://www.gnu.org/licenses/>.  *
 ***************************************************************************/
#ifndef ITEMBACKENDEDITOR_H
#define ITEMBACKENDEDITOR_H
#include <QtCore/QAbstractItemModel>

#include <typedefs.h>

//Ring
class PhoneNumber;

class LIB_EXPORT CollectionEditorBase {
public:
   CollectionEditorBase(QAbstractItemModel* m);
   QAbstractItemModel* model() const;

protected:
   QAbstractItemModel* m_pModel;
};

/**
 * This is the class that does the actual work. This class
 * represent a delegate of CollectionInterface. It is usually
 * recommanded to implement this as a private class in the .cpp
 * that implement the CollectionInterface.
 *
 * The rational behind this inversion of responsability layer
 * is to avoid using a template class for CollectionInterface.
 * This would add obstable when implementing objects using it due
 * to C++11 lack of generic template polymorphism. A base class
 * extended by the template call also doesn't solve those issues.
 */
template<typename T>
class LIB_EXPORT CollectionEditor : public CollectionEditorBase {
   friend class CollectionInterface;
public:
   CollectionEditor(CollectionMediator<T>* m);
   virtual ~CollectionEditor();

   CollectionMediator<T>* mediator() const;

   virtual bool save(const T* item) =0;
   virtual bool append(const T* item) =0;
   virtual bool batchSave(const QList<T*> contacts);
   virtual bool remove(T* item);

   ///Edit 'item', the implementation may be a GUI or something else
   virtual bool edit       ( T*       item     ) = 0;
   ///Add a new item to the backend
   virtual bool addNew     ( T*       item     ) = 0;

   ///Add a new phone number to an existing item
   virtual bool addPhoneNumber( T*       item , PhoneNumber* number );

private:
   /**
    * Return the items generated by this backend. This overloaded
    * version also make sure that the type is compatible.
    */
   QVector<T*> items() const;

   /**
    * Return the metatype of this editor
    */
   QMetaObject metaObject();

   /**
    * Return the items generated by this backend
    */
   virtual QVector<T*> items() const = 0;

   //Attributes
   CollectionMediator<T>* m_pMediator;
};

#include "itembackendeditor.hpp"

#endif